version: '3.8'

services:
  luna-kitty-spin:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "42891:42891"
    environment:
      - NODE_ENV=production
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M 